name: Deployment

# eventos
on:
  push:
    branches:
      - main

# jobs en el flujo de trabajo
jobs:
  build-app:
    # entorno
    runs-on: ubuntu-latest

    # pasos
    steps:
    - name: Checkout of source code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: AlejandrVilla/GKE-deploy@main
      env:
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
        ZONE_NAME: us-central1-c
      with:
        args: apply -f packaging/k8s/manifests/ -n prod

    - name: Validate Deployment
      run: kubectl get pods

    # - name: Check versions
    #   run: bash pre-init.sh
      
    # - name: config
    #   run: bash config.sh

    # - name: Clean
    #   run: bash pre-build.sh

    # - name: Build and push
    #   run: bash docker-build-push.sh

    #- name: destroy
    # run: destroy.sh
